apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cli-deployment
  labels:
    app: cli
spec:
  selector:
    matchLabels:
      app: cli
  replicas: 1
  template:
    metadata:
      labels:
        app: cli
    spec:
      containers:
      - name: cli
        image: local/cli
        imagePullPolicy: Never
        ports:
        - name: cli-service
          containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: cli-service
spec:
  type: NodePort
  selector:
    app: cli
  ports:
  - port: 3030
    targetPort: cli-service